id: I47AAE9FA
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T13:25:06+00:00'
last_modified: '2022-06-07T13:59:48.177708+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3968
  title: རྣལ་འབྱོར་གྱི་དབང་ཕྱུག་བཞད་པ་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་སོགས་རྣམ་ཐར་ཁག་ཅིག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A75F:
      image_group_id: I1KG4026
      title: ''
      total_pages: 380
      order: 1
      base_file: A75F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
