id: P001676
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3968
  title: རྣལ་འབྱོར་གྱི་དབང་ཕྱུག་བཞད་པ་རྡོ་རྗེའི་རྣམ་པར་ཐར་པ་སོགས་རྣམ་ཐར་ཁག་ཅིག
  author: ''
  volumes:
    731b3cc8dba0494590f6a458e338aed2:
      image_group_id: I1KG4026
      title: ''
      volume_number: 1
      total_pages: 380
